### ISSUE TITLE
python vision handling + tag scanning

### ISSUE THREAD

**Issue by Fabio53443** [Fabio53443/Rosita-CoppeliaSim#2]
get an image from the kinect into the python workspace, possibly in a tag-scanning library of sorts.

**Comment by ruryx00** [comment]
```python
visionSensorHandle = sim.getObject('/VisionSensor')
img, [resX, resY] = sim.getVisionSensorImg(visionSensorHandle)
img = np.frombuffer(img, dtype=np.uint8).reshape(resY, resX, 3)
```

**Comment by ruryx00** [comment]
https://manual.coppeliarobotics.com/en/apiFunctions.htm

**Comment by Fabio53443** [comment]
IDEA: save image in a temp/persistent folder then pass the image as a file to the qr library

**Comment by Fabio53443** [comment]
Done
